import json
import re
from typing import Any

import numpy as np
from llm_sdk import Small_LLM_Model

from .aliases import apply_aliases
from .constrain import (
    ClosedChoice,
    masked_argmax,
    number_token_ids,
    string_tokens,
)
from .vocab import token_to_bytes

# Upper bound on tokens generated for a single slot (name or argument) so a
# model that never closes a value still stops after 64 tokens
MAX_SLOT_TOKENS = 64

# Repairs whatever number charset generated by model i.e. 1.2.3 = 1.2
NUMBER_PATTERN = re.compile(rb"-?\d+(?:\.\d+)?")

# A worked example with a made-up function, so the model sees that a
# described value ("whitespace runs") becomes the value itself (\s+)
EXAMPLE = (
    "Example:\n"
    "Request: Replace every whitespace run in 'a  b c' with underscores\n"
    'Answer: {"name": "fn_replace_pattern", "parameters": '
    '{"text": "a  b c", "pattern": "\\\\s+", "replacement": "_"}}'
)


def build_system_prompt(functions: list[dict[str, Any]]) -> str:
    """
    Passes in an organized catalouge of functions
    and returns the system prompt
    """
    catalogue = "\n".join(
        "- {name}({params}): {description}".format(
            name=function["name"],
            params=", ".join(
                f"{key}: {spec['type']}"
                for key, spec in function["parameters"].items()
            ),
            description=function["description"],
        )
        for function in functions
    )
    return (
        "You are a function calling assistant.\n"
        "Choose the function that answers the request and fill in its "
        "arguments. Arguments are JSON values: when a request describes a "
        "value instead of quoting it, write the actual value (a regex "
        "pattern, a symbol), and escape backslashes.\n"
        "Do not answer the request yourself.\n"
        "Available functions:\n"
        f"{catalogue}\n\n"
        f"{EXAMPLE}"
    )


def build_chat_prompt(system_prompt: str, user_prompt: str) -> str:
    """
    Skips thinking and combines the system and user prompts
    by wrapping them in Qwen3's chat template
    """
    return (
        f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
        f"<|im_start|>user\n{user_prompt}<|im_end|>\n"
        f"<|im_start|>assistant\n<think>\n\n</think>\n\n"
    )


def _next_logits(model: Small_LLM_Model, prefix: bytes) -> list[float]:
    """Obtains the next logits according to a prefix"""
    text = prefix.decode("utf-8", errors="ignore")
    return model.get_logits_from_input_ids(model.encode(text)[0].tolist())


def _fill_choice(
    model: Small_LLM_Model, prefix: bytes, slot: ClosedChoice
) -> bytes:
    """Adds tokens onto a prefix, it gives up if it reaches max tokens"""
    for _ in range(MAX_SLOT_TOKENS):
        if slot.match is not None:
            return prefix
        logits = _next_logits(model, prefix)
        token_id = masked_argmax(logits, slot.allowed())
        slot.advance(token_id)
        prefix += token_to_bytes(token_id)
    raise RuntimeError("closed choice did not settle within the token budget")


def _fill_string(model: Small_LLM_Model, prefix: bytes) -> tuple[str, bytes]:
    """
    Generates JSON string content until the model closes the string.
    Backslash escapes are allowed as long as they stay valid JSON (e.g.
    \\\\d, the JSON form of the regex \\d), and the value is unescaped
    before it is returned.
    """
    escaped = False
    value = b""
    for _ in range(MAX_SLOT_TOKENS):
        content, closing, allowed = string_tokens(escaped)
        logits = _next_logits(model, prefix)
        token_id = masked_argmax(logits, allowed)
        if token_id in closing:
            value += closing[token_id]
            prefix += closing[token_id]
            break
        data = token_to_bytes(token_id)
        escaped = content[token_id]
        value += data
        prefix += data
    if escaped:
        # Out of budget right after a backslash: drop it to stay valid JSON
        value = value[:-1]
        prefix = prefix[:-1]
    text = value.decode("utf-8", errors="ignore")
    return json.loads(f'"{text}"').strip(), prefix


def _fill_number(model: Small_LLM_Model, prefix: bytes) -> tuple[float, bytes]:
    """
    Fills in number patterns and stops once the model's pick
    isn't a number token
    """
    allowed = set(number_token_ids())
    raw = b""
    for _ in range(MAX_SLOT_TOKENS):
        logits = _next_logits(model, prefix)
        if raw and int(np.argmax(logits)) not in allowed:
            break
        token_id = masked_argmax(logits, allowed)
        data = token_to_bytes(token_id)
        raw += data
        prefix += data
    match = NUMBER_PATTERN.search(raw)
    value = float(match.group()) if match else 0.0
    repaired = repr(value).encode("utf-8")
    return value, prefix[: len(prefix) - len(raw)] + repaired


def generate_call(
    model: Small_LLM_Model,
    system_prompt: str,
    functions: list[dict[str, Any]],
    user_prompt: str,
) -> dict[str, Any]:
    """Generates the JSON skeleton and allows the model to
    fill in the slots.
    """
    by_name = {function["name"]: function for function in functions}
    prefix = build_chat_prompt(system_prompt, user_prompt).encode("utf-8")
    prefix += b'{"name": "'

    name_slot = ClosedChoice(options=list(by_name), terminator='"')
    prefix = _fill_choice(model, prefix, name_slot)
    name = name_slot.value()

    prefix += b', "parameters": {'
    parameters: dict[str, Any] = {}
    declared = by_name[name]["parameters"].items()
    for position, (key, spec) in enumerate(declared):
        if position:
            prefix += b", "
        prefix += f'"{key}": '.encode("utf-8")
        kind = spec["type"]
        value: str | float | bool
        if kind == "string":
            prefix += b'"'
            value, prefix = _fill_string(model, prefix)
            prefix += b'"'
        elif kind == "number":
            value, prefix = _fill_number(model, prefix)
        else:
            flag = ClosedChoice(options=["true", "false"], terminator="")
            prefix = _fill_choice(model, prefix, flag)
            value = flag.value() == "true"
        parameters[key] = value

    parameters = apply_aliases(user_prompt, by_name[name], parameters)
    return {"prompt": user_prompt, "name": name, "parameters": parameters}
