import json
import re
from typing import Any

import numpy as np
from llm_sdk import Small_LLM_Model

from .constrain import (
    ClosedChoice,
    integer_token_ids,
    masked_argmax,
    number_opening_ids,
    number_token_ids,
    string_opening_tokens,
    string_tokens,
)
from .vocab import token_to_bytes

# Upper bound on tokens generated for a single slot (name or argument) so a
# model that never closes a value still stops after 64 tokens
MAX_SLOT_TOKENS = 64

# Repairs whatever number charset generated by model i.e. 1.2.3 = 1.2
NUMBER_PATTERN = re.compile(rb"-?\d+(?:\.\d+)?")

# Same repair for integers, so 1-2 = 1
INTEGER_PATTERN = re.compile(rb"-?\d+")

# Two worked examples with a made-up function, so the model sees that a
# described value becomes the value itself: a character class ([,;]+)
# and an escaped regex (\s+)
EXAMPLE = (
    "Examples:\n"
    "Request: Replace every run of commas or semicolons in 'a,;b;c' "
    "with dashes\n"
    'Answer: {"name": "fn_replace_pattern", "parameters": '
    '{"text": "a,;b;c", "pattern": "[,;]+", "replacement": "-"}}\n'
    "Request: Replace every whitespace run in 'a  b c' with underscores\n"
    'Answer: {"name": "fn_replace_pattern", "parameters": '
    '{"text": "a  b c", "pattern": "\\\\s+", "replacement": "_"}}'
)


def build_system_prompt(functions: list[dict[str, Any]]) -> str:
    """
    Passes in an organized catalouge of functions
    and returns the system prompt
    """
    catalogue = "\n".join(
        "- {name}({params}): {description}".format(
            name=function["name"],
            params=", ".join(
                f"{key}: {spec['type']}"
                for key, spec in function["parameters"].items()
            ),
            description=function["description"],
        )
        for function in functions
    )
    return (
        "You are a function calling assistant.\n"
        "Choose the function that answers the request and fill in its "
        "arguments. Arguments are JSON values: when a request describes a "
        "value instead of quoting it, write the actual value (a regex "
        "pattern, a symbol), and escape backslashes.\n"
        "Do not answer the request yourself.\n"
        "Available functions:\n"
        f"{catalogue}\n\n"
        f"{EXAMPLE}"
    )


def build_chat_prompt(system_prompt: str, user_prompt: str) -> str:
    """
    Skips thinking and combines the system and user prompts
    by wrapping them in Qwen3's chat template
    """
    return (
        f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
        f"<|im_start|>user\n{user_prompt}<|im_end|>\n"
        f"<|im_start|>assistant\n<think>\n\n</think>\n\n"
    )


def _next_logits(model: Small_LLM_Model, prefix: bytes) -> list[float]:
    """Obtains the next logits according to a prefix"""
    text = prefix.decode("utf-8", errors="ignore")
    return model.get_logits_from_input_ids(model.encode(text)[0].tolist())


def _fill_choice(
    model: Small_LLM_Model, prefix: bytes, slot: ClosedChoice
) -> bytes:
    """Adds tokens onto a prefix, it gives up if it reaches max tokens"""
    for _ in range(MAX_SLOT_TOKENS):
        if slot.match is not None:
            return prefix
        logits = _next_logits(model, prefix)
        token_id = masked_argmax(logits, slot.allowed())
        slot.advance(token_id)
        prefix += token_to_bytes(token_id)
    raise RuntimeError("closed choice did not settle within the token budget")


def _fill_string(model: Small_LLM_Model, prefix: bytes) -> tuple[str, bytes]:
    """
    Generates a JSON string from the colon until the model closes it.
    The first token carries the opening quote, so the model can pick
    the merged token it prefers (' "/' rather than ' "' then '/').
    Backslash escapes are allowed as long as they stay valid JSON (e.g.
    \\\\d, the JSON form of the regex \\d), and the value is unescaped
    before it is returned.
    """
    opening, opening_closed = string_opening_tokens()
    logits = _next_logits(model, prefix)
    token_id = masked_argmax(logits, set(opening) | set(opening_closed))
    prefix += b' "'
    if token_id in opening_closed:
        value = opening_closed[token_id]
        text = value.decode("utf-8", errors="ignore")
        return json.loads(f'"{text}"').strip(), prefix + value
    value = token_to_bytes(token_id).removeprefix(b" ")[1:]
    prefix += value
    escaped = opening[token_id]
    for _ in range(MAX_SLOT_TOKENS - 1):
        content, closing, allowed = string_tokens(escaped)
        logits = _next_logits(model, prefix)
        token_id = masked_argmax(logits, allowed)
        if token_id in closing:
            value += closing[token_id]
            prefix += closing[token_id]
            break
        data = token_to_bytes(token_id)
        escaped = content[token_id]
        value += data
        prefix += data
    if escaped:
        # Out of budget right after a backslash: drop it to stay valid JSON
        value = value[:-1]
        prefix = prefix[:-1]
    text = value.decode("utf-8", errors="ignore")
    return json.loads(f'"{text}"').strip(), prefix


def _fill_number(
    model: Small_LLM_Model, prefix: bytes, integer: bool = False
) -> tuple[float | int, bytes]:
    """
    Fills in number patterns and stops once the model's pick
    isn't a number token. With integer set, a decimal point is
    never allowed and the value is returned as an int
    """
    allowed = set(integer_token_ids() if integer else number_token_ids())
    start = len(prefix)
    # The first token may carry the space after the colon, so the model
    # can write its preferred ' -' and keep a negative sign
    logits = _next_logits(model, prefix)
    token_id = masked_argmax(logits, number_opening_ids(integer))
    raw = token_to_bytes(token_id).removeprefix(b" ")
    prefix += token_to_bytes(token_id)
    for _ in range(MAX_SLOT_TOKENS - 1):
        logits = _next_logits(model, prefix)
        if raw and int(np.argmax(logits)) not in allowed:
            break
        token_id = masked_argmax(logits, allowed)
        data = token_to_bytes(token_id)
        raw += data
        prefix += data
    pattern = INTEGER_PATTERN if integer else NUMBER_PATTERN
    match = pattern.search(raw)
    value: float | int
    if integer:
        value = int(match.group()) if match else 0
    else:
        value = float(match.group()) if match else 0.0
    repaired = repr(value).encode("utf-8")
    return value, prefix[:start] + b" " + repaired


def generate_call(
    model: Small_LLM_Model,
    system_prompt: str,
    functions: list[dict[str, Any]],
    user_prompt: str,
) -> dict[str, Any]:
    """Generates the JSON skeleton and allows the model to
    fill in the slots.
    """
    by_name = {function["name"]: function for function in functions}
    prefix = build_chat_prompt(system_prompt, user_prompt).encode("utf-8")
    prefix += b'{"name": "'

    # The terminator includes the comma: the model writes '",' as one
    # token, so ending on a lone '"' would push it to a longer name
    name_slot = ClosedChoice(options=list(by_name), terminator='",')
    prefix = _fill_choice(model, prefix, name_slot)
    name = name_slot.value()

    prefix += b' "parameters": {'
    parameters: dict[str, Any] = {}
    declared = by_name[name]["parameters"].items()
    for position, (key, spec) in enumerate(declared):
        if position:
            prefix += b", "
        # No space after the colon: the value's first token carries it
        prefix += f'"{key}":'.encode("utf-8")
        kind = spec["type"]
        value: str | float | int | bool
        if kind == "string":
            value, prefix = _fill_string(model, prefix)
            prefix += b'"'
        elif kind == "number":
            value, prefix = _fill_number(model, prefix)
        elif kind == "integer":
            value, prefix = _fill_number(model, prefix, integer=True)
        else:
            prefix += b" "
            flag = ClosedChoice(options=["true", "false"], terminator="")
            prefix = _fill_choice(model, prefix, flag)
            value = flag.value() == "true"
        parameters[key] = value

    return {"prompt": user_prompt, "name": name, "parameters": parameters}
